//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfEnglishSchoolApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnglishSchoolABCEntities : DbContext
    {
        public EnglishSchoolABCEntities()
            : base("name=EnglishSchoolABCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientType> ClientTypes { get; set; }
        public virtual DbSet<Complect> Complects { get; set; }
        public virtual DbSet<Developer> Developers { get; set; }
        public virtual DbSet<Good> Goods { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sell> Sells { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<TimeSheet> TimeSheets { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<WorkerSpec> WorkerSpecs { get; set; }
    }
}
