//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfEnglishSchoolApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerSpec
    {
        public int Id { get; set; }
        public int SpecialityId { get; set; }
        public int WorkerId { get; set; }
    
        public virtual Speciality Speciality { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
